// Every country/territory the bundled globe map (world-atlas's Natural Earth
// 1:110m data, public domain) actually draws, paired with its ISO 3166-1
// numeric id -- the same id world-atlas uses for each feature -- and its
// ISO 3166-1 alpha-2 code, which is what every other per-country table in
// this app (pulseCountries.ts, pulseBlocs.ts, freightNotes.ts, the backend's
// country.ts, etc.) keys on. This is the single source every one of those
// tables, plus PulseGlobe.tsx's click/hover handling, should derive from --
// not a second, hand-typed list that could drift out of sync with it.
//
// Antarctica (numeric id 10) and the three features the map draws without a
// numeric id at all (Northern Cyprus, Somaliland, Kosovo -- disputed/
// unrecognized territories Natural Earth still renders, but ISO never
// assigned a code to) are intentionally left out: this app has no honest
// code to give them, so they stay hoverable-but-unselectable on the globe,
// the same way they were before this file existed.
//
// Names are copied verbatim from world-atlas's own `properties.name` (the
// same text the globe's hover label already showed for these countries) --
// not retyped or "corrected" by hand, so there is one real source for a
// country's display name, not two that can disagree.
export const WORLD_COUNTRIES: { id: number; code: string; name: string }[] = [
  { id: 4, code: 'AF', name: 'Afghanistan' },
  { id: 8, code: 'AL', name: 'Albania' },
  { id: 12, code: 'DZ', name: 'Algeria' },
  { id: 24, code: 'AO', name: 'Angola' },
  { id: 31, code: 'AZ', name: 'Azerbaijan' },
  { id: 32, code: 'AR', name: 'Argentina' },
  { id: 36, code: 'AU', name: 'Australia' },
  { id: 40, code: 'AT', name: 'Austria' },
  { id: 44, code: 'BS', name: 'Bahamas' },
  { id: 50, code: 'BD', name: 'Bangladesh' },
  { id: 51, code: 'AM', name: 'Armenia' },
  { id: 56, code: 'BE', name: 'Belgium' },
  { id: 64, code: 'BT', name: 'Bhutan' },
  { id: 68, code: 'BO', name: 'Bolivia' },
  { id: 70, code: 'BA', name: 'Bosnia and Herz.' },
  { id: 72, code: 'BW', name: 'Botswana' },
  { id: 76, code: 'BR', name: 'Brazil' },
  { id: 84, code: 'BZ', name: 'Belize' },
  { id: 90, code: 'SB', name: 'Solomon Is.' },
  { id: 96, code: 'BN', name: 'Brunei' },
  { id: 100, code: 'BG', name: 'Bulgaria' },
  { id: 104, code: 'MM', name: 'Myanmar' },
  { id: 108, code: 'BI', name: 'Burundi' },
  { id: 112, code: 'BY', name: 'Belarus' },
  { id: 116, code: 'KH', name: 'Cambodia' },
  { id: 120, code: 'CM', name: 'Cameroon' },
  { id: 124, code: 'CA', name: 'Canada' },
  { id: 140, code: 'CF', name: 'Central African Rep.' },
  { id: 144, code: 'LK', name: 'Sri Lanka' },
  { id: 148, code: 'TD', name: 'Chad' },
  { id: 152, code: 'CL', name: 'Chile' },
  { id: 156, code: 'CN', name: 'China' },
  { id: 158, code: 'TW', name: 'Taiwan' },
  { id: 170, code: 'CO', name: 'Colombia' },
  { id: 178, code: 'CG', name: 'Congo' },
  { id: 180, code: 'CD', name: 'Dem. Rep. Congo' },
  { id: 188, code: 'CR', name: 'Costa Rica' },
  { id: 191, code: 'HR', name: 'Croatia' },
  { id: 192, code: 'CU', name: 'Cuba' },
  { id: 196, code: 'CY', name: 'Cyprus' },
  { id: 203, code: 'CZ', name: 'Czechia' },
  { id: 204, code: 'BJ', name: 'Benin' },
  { id: 208, code: 'DK', name: 'Denmark' },
  { id: 214, code: 'DO', name: 'Dominican Rep.' },
  { id: 218, code: 'EC', name: 'Ecuador' },
  { id: 222, code: 'SV', name: 'El Salvador' },
  { id: 226, code: 'GQ', name: 'Eq. Guinea' },
  { id: 231, code: 'ET', name: 'Ethiopia' },
  { id: 232, code: 'ER', name: 'Eritrea' },
  { id: 233, code: 'EE', name: 'Estonia' },
  { id: 238, code: 'FK', name: 'Falkland Is.' },
  { id: 242, code: 'FJ', name: 'Fiji' },
  { id: 246, code: 'FI', name: 'Finland' },
  { id: 250, code: 'FR', name: 'France' },
  { id: 260, code: 'TF', name: 'Fr. S. Antarctic Lands' },
  { id: 262, code: 'DJ', name: 'Djibouti' },
  { id: 266, code: 'GA', name: 'Gabon' },
  { id: 268, code: 'GE', name: 'Georgia' },
  { id: 270, code: 'GM', name: 'Gambia' },
  { id: 275, code: 'PS', name: 'Palestine' },
  { id: 276, code: 'DE', name: 'Germany' },
  { id: 288, code: 'GH', name: 'Ghana' },
  { id: 300, code: 'GR', name: 'Greece' },
  { id: 304, code: 'GL', name: 'Greenland' },
  { id: 320, code: 'GT', name: 'Guatemala' },
  { id: 324, code: 'GN', name: 'Guinea' },
  { id: 328, code: 'GY', name: 'Guyana' },
  { id: 332, code: 'HT', name: 'Haiti' },
  { id: 340, code: 'HN', name: 'Honduras' },
  { id: 348, code: 'HU', name: 'Hungary' },
  { id: 352, code: 'IS', name: 'Iceland' },
  { id: 356, code: 'IN', name: 'India' },
  { id: 360, code: 'ID', name: 'Indonesia' },
  { id: 364, code: 'IR', name: 'Iran' },
  { id: 368, code: 'IQ', name: 'Iraq' },
  { id: 372, code: 'IE', name: 'Ireland' },
  { id: 376, code: 'IL', name: 'Israel' },
  { id: 380, code: 'IT', name: 'Italy' },
  { id: 384, code: 'CI', name: "Côte d'Ivoire" },
  { id: 388, code: 'JM', name: 'Jamaica' },
  { id: 392, code: 'JP', name: 'Japan' },
  { id: 398, code: 'KZ', name: 'Kazakhstan' },
  { id: 400, code: 'JO', name: 'Jordan' },
  { id: 404, code: 'KE', name: 'Kenya' },
  { id: 408, code: 'KP', name: 'North Korea' },
  { id: 410, code: 'KR', name: 'South Korea' },
  { id: 414, code: 'KW', name: 'Kuwait' },
  { id: 417, code: 'KG', name: 'Kyrgyzstan' },
  { id: 418, code: 'LA', name: 'Laos' },
  { id: 422, code: 'LB', name: 'Lebanon' },
  { id: 426, code: 'LS', name: 'Lesotho' },
  { id: 428, code: 'LV', name: 'Latvia' },
  { id: 430, code: 'LR', name: 'Liberia' },
  { id: 434, code: 'LY', name: 'Libya' },
  { id: 440, code: 'LT', name: 'Lithuania' },
  { id: 442, code: 'LU', name: 'Luxembourg' },
  { id: 450, code: 'MG', name: 'Madagascar' },
  { id: 454, code: 'MW', name: 'Malawi' },
  { id: 458, code: 'MY', name: 'Malaysia' },
  { id: 466, code: 'ML', name: 'Mali' },
  { id: 478, code: 'MR', name: 'Mauritania' },
  { id: 484, code: 'MX', name: 'Mexico' },
  { id: 496, code: 'MN', name: 'Mongolia' },
  { id: 498, code: 'MD', name: 'Moldova' },
  { id: 499, code: 'ME', name: 'Montenegro' },
  { id: 504, code: 'MA', name: 'Morocco' },
  { id: 508, code: 'MZ', name: 'Mozambique' },
  { id: 512, code: 'OM', name: 'Oman' },
  { id: 516, code: 'NA', name: 'Namibia' },
  { id: 524, code: 'NP', name: 'Nepal' },
  { id: 528, code: 'NL', name: 'Netherlands' },
  { id: 540, code: 'NC', name: 'New Caledonia' },
  { id: 548, code: 'VU', name: 'Vanuatu' },
  { id: 554, code: 'NZ', name: 'New Zealand' },
  { id: 558, code: 'NI', name: 'Nicaragua' },
  { id: 562, code: 'NE', name: 'Niger' },
  { id: 566, code: 'NG', name: 'Nigeria' },
  { id: 578, code: 'NO', name: 'Norway' },
  { id: 586, code: 'PK', name: 'Pakistan' },
  { id: 591, code: 'PA', name: 'Panama' },
  { id: 598, code: 'PG', name: 'Papua New Guinea' },
  { id: 600, code: 'PY', name: 'Paraguay' },
  { id: 604, code: 'PE', name: 'Peru' },
  { id: 608, code: 'PH', name: 'Philippines' },
  { id: 616, code: 'PL', name: 'Poland' },
  { id: 620, code: 'PT', name: 'Portugal' },
  { id: 624, code: 'GW', name: 'Guinea-Bissau' },
  { id: 626, code: 'TL', name: 'Timor-Leste' },
  { id: 630, code: 'PR', name: 'Puerto Rico' },
  { id: 634, code: 'QA', name: 'Qatar' },
  { id: 642, code: 'RO', name: 'Romania' },
  { id: 643, code: 'RU', name: 'Russia' },
  { id: 646, code: 'RW', name: 'Rwanda' },
  { id: 682, code: 'SA', name: 'Saudi Arabia' },
  { id: 686, code: 'SN', name: 'Senegal' },
  { id: 688, code: 'RS', name: 'Serbia' },
  { id: 694, code: 'SL', name: 'Sierra Leone' },
  { id: 703, code: 'SK', name: 'Slovakia' },
  { id: 704, code: 'VN', name: 'Vietnam' },
  { id: 705, code: 'SI', name: 'Slovenia' },
  { id: 706, code: 'SO', name: 'Somalia' },
  { id: 710, code: 'ZA', name: 'South Africa' },
  { id: 716, code: 'ZW', name: 'Zimbabwe' },
  { id: 724, code: 'ES', name: 'Spain' },
  { id: 728, code: 'SS', name: 'S. Sudan' },
  { id: 729, code: 'SD', name: 'Sudan' },
  { id: 732, code: 'EH', name: 'W. Sahara' },
  { id: 740, code: 'SR', name: 'Suriname' },
  { id: 748, code: 'SZ', name: 'eSwatini' },
  { id: 752, code: 'SE', name: 'Sweden' },
  { id: 756, code: 'CH', name: 'Switzerland' },
  { id: 760, code: 'SY', name: 'Syria' },
  { id: 762, code: 'TJ', name: 'Tajikistan' },
  { id: 764, code: 'TH', name: 'Thailand' },
  { id: 768, code: 'TG', name: 'Togo' },
  { id: 780, code: 'TT', name: 'Trinidad and Tobago' },
  { id: 784, code: 'AE', name: 'United Arab Emirates' },
  { id: 788, code: 'TN', name: 'Tunisia' },
  { id: 792, code: 'TR', name: 'Turkey' },
  { id: 795, code: 'TM', name: 'Turkmenistan' },
  { id: 800, code: 'UG', name: 'Uganda' },
  { id: 804, code: 'UA', name: 'Ukraine' },
  { id: 807, code: 'MK', name: 'Macedonia' },
  { id: 818, code: 'EG', name: 'Egypt' },
  { id: 826, code: 'GB', name: 'United Kingdom' },
  { id: 834, code: 'TZ', name: 'Tanzania' },
  { id: 840, code: 'US', name: 'United States of America' },
  { id: 854, code: 'BF', name: 'Burkina Faso' },
  { id: 858, code: 'UY', name: 'Uruguay' },
  { id: 860, code: 'UZ', name: 'Uzbekistan' },
  { id: 862, code: 'VE', name: 'Venezuela' },
  { id: 887, code: 'YE', name: 'Yemen' },
  { id: 894, code: 'ZM', name: 'Zambia' },
];

// Keyed views other modules actually want -- 'US' is deliberately present
// here (the globe needs its id) but callers that build a display-label table
// (pulseCountries.ts's COUNTRY_LABELS) filter it back out, since no action or
// headline is ever tagged with 'US' and it has its own hardcoded "United
// States" treatment wherever it's shown.
export const WORLD_ID_TO_CODE: Record<number, string> = Object.fromEntries(WORLD_COUNTRIES.map((c) => [c.id, c.code]));
export const WORLD_CODE_TO_ID = new Map<string, number>(WORLD_COUNTRIES.map((c) => [c.code, c.id]));
export const WORLD_NAME_FOR: Record<string, string> = Object.fromEntries(WORLD_COUNTRIES.map((c) => [c.code, c.name]));
